### ISSUE TITLE
No public method 'raiseToast' is defined on class com.appiumpro.the_app.MainApplication

### ISSUE THREAD

**Issue by itkhanz** [appium-pro/TheApp#3]
Hi,
I was following through Jonathan Lipps's advanced appium course on Linkedin Learning. Also described in blog:
https://www.headspin.io/blog/calling-methods-inside-your-app-from-appium

In the lecture titled "**State Shortcut3: Application backdoors**", call to the application internal method **raiseToast** is made which should display a toast message on the screen titled "**Hello from the test script!**".

I initialized my driver with Espresso. Here is the test code:
```
ImmutableMap<String, Object> scriptArgs = ImmutableMap.of(
                "target", "application",
                "methods", Arrays.asList(ImmutableMap.of(
                        "name", "raiseToast",
                        "args", Arrays.asList(ImmutableMap.of(
                                "value", "Hello from the test script!",
                                "type", "String"
                        ))
                ))
        );

driver.executeScript("mobile: backdoor", scriptArgs);
```

When i executed my tests, I received the following error:
**_org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: No public method 'raiseToast' is defined on class com.appiumpro.the_app.MainApplication or its parents which takes [class java.lang.String] arguments_**

I also tried to look for this method `raiseToast` in the application source code but i am unable to see this method both in the current version as well as deprecated version of the TheApp.

My test environment is setup as:

- JDK 11.0.2
- Appium 2.0.0-rc.3
- appium-java-client 8.5.1
- appium espresso driver 2.23.1
- selenium-java 4.9.1
- Node v18.16.0
- NPM 9.6.7
- macOS Ventura 13.4
- Android emulator Pixel 5 with android 13

Here are the full logs of appium java client:

```
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: No public method 'raiseToast' is defined on class com.appiumpro.the_app.MainApplication or its parents which takes [class java.lang.String] arguments
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '11.0.2'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [6cc38515-b7de-4c63-8a9b-1816dd1ce593, executeScript {script=mobile: backdoor, args=[{methods=[{name=raiseToast, args=[{type=String, value=Hello from the test script!}]}], target=application}]}]
Capabilities {appium:adbExecTimeout: 30000, appium:app: /Users/xxxx/dev/appium/Appi..., appium:autoGrantPermissions: true, appium:autoWebviewTimeout: 10000, appium:automationName: Espresso, appium:chromedriverExecutableDir: /Users/xxxx/dev/appium/Appi..., appium:udid: emulator-5554, platformName: ANDROID}
Session ID: 6cc38515-b7de-4c63-8a9b-1816dd1ce593

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:199)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:132)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:51)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:191)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:531)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:476)
	at com.itkhanz.linkedin.advancedappium.tests.BackDoorTest.testBackdoor(BackDoorTest.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.testng.TestRunner.privateRun(TestRunner.java:848)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
	at org.testng.SuiteRunner.run(SuiteRunner.java:336)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
	at org.testng.TestNG.runSuites(TestNG.java:1114)
	at org.testng.TestNG.run(TestNG.java:1082)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
```

Attached you will also find the appium server logs
[appium-espressp-logs.txt](https://github.com/appium-pro/TheApp/files/11859759/appium-espressp-logs.txt)

If we look closely at the logs, I can see that the appium sent the request to server but recieved response with staus code 500.

```
[HTTP] {"script":"mobile: backdoor","args":[{"methods":[{"name":"raiseToast","args":[{"type":"String","value":"Hello from the test script!"}]}],"target":"application"}]}
[debug] [EspressoDriver@478c (6cc38515)] Calling AppiumDriver.execute() with args: ["mobile: backdoor",[{"methods":[{"name":"raiseToast","args":[{"type":"String","value":"Hello from the test script!"}]}],"target":"application"}],"6cc38515-b7de-4c63-8a9b-1816dd1ce593"]
[EspressoDriver@478c (6cc38515)] Executing native command 'mobile: backdoor'
[debug] [EspressoDriver@478c (6cc38515)] Proxying [POST /appium/execute_mobile/backdoor] to [POST http://127.0.0.1:8301/session/b2686608-63f7-43ad-ad08-191fe9cca5e8/appium/execute_mobile/backdoor] with body: {"target":"application","methods":[{"name":"raiseToast","args":[{"type":"String","value":"Hello from the test script!"}]}]}
[EspressoDriver@478c (6cc38515)] Got response with status 500: {"id":"666996bc-9b6d-4c4a-8d48-2e94b0a3a75f","sessionId":"b2686608-63f7-43ad-ad08-191fe9cca5e8","value":{"error":"unknown error","message":"No public method 'raiseToast' is defined on class com.appiumpro.the_app.MainApplication or its parents which takes [class java.lang.String] arguments","stacktrace":"io.appium.espressoserver.lib.handlers.exceptions.AppiumException: No public method 'raiseToast' is defined on class com.appiumpro.the_app.MainApplication or its parents which takes [class java.lang.String] arguments\n\tat io.appium.espressoserver.lib.helpers.InvocationOperation.findCompatibleMethod(InvocationOperation.java:76)\n\tat io.appium.espressoserver.lib.helpers.InvocationOperation.apply(InvocationOperation.java:43)\n\tat io.appium.espressoserver.lib.handlers.MobileBackdoor.invokeBackdoorMethods(MobileBackdoor.kt:43)\n\tat io.appium.espressoserver.lib.handlers.MobileBackdoor.handleInternal(MobileBackdoor.kt:21)\n\tat io.appium.espressoserver.lib.handlers.MobileBackdoor.handleInternal(MobileBackdoor.k...
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[debug] [EspressoDriver@478c (6cc38515)] Encountered internal error running command: An unknown server-side error occurred while processing the command. Original error: No public method 'raiseToast' is defined on class com.appiumpro.the_app.MainApplication or its parents which takes [class java.lang.String] arguments
[debug] [EspressoDriver@478c (6cc38515)] io.appium.espressoserver.lib.handlers.exceptions.AppiumException: No public method 'raiseToast' is defined on class com.appiumpro.the_app.MainApplication or its parents which takes [class java.lang.String] arguments
```

Could you please verify if this method does not exist in the updated version of the app? and is there any alternative way to test the backdoor method of appium using this application?

**Comment by jlipps** [comment]
You are correct that this feature was missed in the rewrite. I'll get to adding it soon. Thanks for the heads up!

**Comment by jlipps** [comment]
the `raiseToast` method is back now in the `1.12.0` app release
